name: Mini_Bill
description: Mini Pos Demo
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.16.0"

dependencies:
  file_picker: ^4.5.1
  flutter:
    sdk: flutter
  hive: ^2.1.0
  image_cropper: ^1.5.1
  image_picker: ^0.8.5
  intl: ^0.17.0
  open_file: ^3.2.1
  path_provider: ^2.0.2
  printing: ^5.7.5
  shared_preferences: ^2.0.13
  url_launcher: ^6.0.6
  hive_flutter: ^1.1.0
  autocomplete_textfield_ns: ^2.0.0
  lottie: ^1.3.0
  fluttertoast: ^8.0.9
  provider: ^6.0.3
  sqflite: ^2.2.6
  infinite_scroll_pagination: ^3.2.0
  pagination_view: ^2.0.0
  faker: ^2.1.0
  firebase_core: ^2.8.0
  firebase_database: ^10.0.16
  sn_progress_dialog : ^1.1.3

dev_dependencies:
  flutter_lints: ^1.0.4
  hive_generator: ^1.1.2
  build_runner: ^2.1.10
  flutter_test:
    sdk: flutter
  test: ^1.16.5

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/db/
    - assets/font/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/roboto_bold.ttf
        - asset: assets/font/roboto_italic.ttf
        - asset: assets/font/roboto_medium.ttf

    - family: ban
      fonts:
        - asset: assets/font/hs_n.ttf
        - asset: assets/font/hs_b.ttf
        - asset: assets/font/hs_m.ttf
