/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class Res {
  static const String backg = "assets/backg.svg";
  static const String bg2 = "assets/bg2.svg";
  static const String calendar = "assets/calendar.svg";
  static const String document = "assets/document.svg";
  static const String garland = "assets/garland.svg";
  static const String hs_b = "assets/font/hs_b.ttf";
  static const String hs_m = "assets/font/hs_m.ttf";
  static const String hs_n = "assets/font/hs_n.ttf";
  static const String invoice = "assets/invoice.svg";
  static const String logo = "assets/logo.png";
  static const String medail = "assets/medail.svg";
  static const String no_internet = "assets/no_internet.json";
  static const String not_found = "assets/not_found.json";
  static const String products = "assets/db/products.sql";
  static const String resume = "assets/resume.svg";
  static const String roboto_bold = "assets/font/roboto_bold.ttf";
  static const String roboto_italic = "assets/font/roboto_italic.ttf";
  static const String roboto_medium = "assets/font/roboto_medium.ttf";
  static const String ss = "assets/ss.png";
  static const String swirls = "assets/swirls.svg";
  static const String swirls1 = "assets/swirls1.svg";
  static const String swirls2 = "assets/swirls2.svg";
  static const String swirls3 = "assets/swirls3.svg";
  static const String warning = "assets/warning.json";
}
